# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PopUp_Add_Firearm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication

import sqlite3
import logging
import traceback


class Ui_PopUp_Add_Firearm(object):
    def __init__(self, firearm_df):
        super().__init__()
        self.firearm_df = firearm_df

    def WriteToDB(self):
        try:
            name = self.Name_TE.toPlainText()
            manufacturer = self.Manufacturer_TE.toPlainText()
            model = self.Model_TE.toPlainText()
            sku = self.SKU_TE.toPlainText()
            caliber = self.Caliber_TE.toPlainText()
            type = self.Type_TE.toPlainText()
            atype = self.Action_TE.toPlainText()
            olength = self.OverLength_TE.toPlainText()
            blength = self.BarrelLength_TE.toPlainText()
            weight = self.Weight_TE.toPlainText()
            twist = self.Twist_TE.toPlainText()
            thread = self.Thread_TE.toPlainText()
            note = self.Notes_TE.toPlainText()
            picture = self.Picture_TE.toPlainText()
            slot15 = self.Slot_27_TE.toPlainText()
            slot16 = self.Slot_16_TE.toPlainText()
            slot17 = self.Slot_17_TE.toPlainText()
            slot18 = self.Slot_18_TE.toPlainText()
            slot19 = self.Slot_19_TE.toPlainText()
            slot20 = self.Slot_20_TE.toPlainText()
            slot21 = self.Slot_21_TE.toPlainText()
            slot22 = self.Slot_22_TE.toPlainText()
            slot23 = self.Slot_23_TE.toPlainText()
            slot24 = self.Slot_24_TE.toPlainText()
            slot25 = self.Slot_25_TE.toPlainText()

            sql = '{}'.format("""INSERT INTO Firearm 
            (Name, Manufacturer, Model, SKU, Caliber, Action_Type, Firearm_Type,   
            Overall_Length_Inch, Barrel_Len_Inch, Weight_Lb, Twist_Rate, Thread_Size, Notes, 
            Picture) 
            VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')"""
            %(name, manufacturer, model, sku, caliber, atype, type, olength, blength, weight,
              twist, thread, note, picture)
                              )

            conn = sqlite3.connect("./DATABASE/TrackerDB.db")
            print("Opened database successfully")
            cursor = conn.cursor()
            cursor.execute(sql)
            conn.commit()
            logging.info(sql)

        except Exception as e:
            print("Exception = ", str(e))
            traceback.print_exc()
            logging.error("ERROR --- ",  str(e))

    def setupUi(self, PopUp_Add_Firearm):
        PopUp_Add_Firearm.setObjectName("PopUp_Add_Firearm")
        PopUp_Add_Firearm.resize(1373, 825)
        PopUp_Add_Firearm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(PopUp_Add_Firearm)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1161, 772))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40,
                                           QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 26, 1, 1, 1)
        # AddFirearm Button
        self.AddFirearm_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.AddFirearm_BTN.setGeometry(QtCore.QRect(1010, 780, 171, 32))
        self.AddFirearm_BTN.setObjectName("AddFirearm_BTN")
        PopUp_Add_Firearm.setCentralWidget(self.centralwidget)
        self.AddFirearm_BTN.clicked.connect(lambda : self.WriteToDB())

        # Name
        self.Name_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Name_LBL.setObjectName("Name_LBL")
        self.gridLayout.addWidget(self.Name_LBL, 0, 0, 1, 1)
        self.Name_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Name_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Name_TE.setObjectName("Name_TE")
        self.gridLayout.addWidget(self.Name_TE, 0, 1, 1, 1)
        # Manufacturer
        self.Manufacturer_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Manufacturer_LBL.setObjectName("Manufacturer_LBL")
        self.gridLayout.addWidget(self.Manufacturer_LBL, 1, 0, 1, 1)
        self.Manufacturer_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Manufacturer_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Manufacturer_TE.setObjectName("Manufacturer_TE")
        self.gridLayout.addWidget(self.Manufacturer_TE, 1, 1, 1, 1)
        # Model
        self.Model_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Model_LBL.setObjectName("Model_LBL")
        self.gridLayout.addWidget(self.Model_LBL, 2, 0, 1, 1)
        self.Model_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Model_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Model_TE.setObjectName("Model_TE")
        self.gridLayout.addWidget(self.Model_TE, 2, 1, 1, 1)
        # SKU
        self.SKU_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.SKU_LBL.setObjectName("SKU_LBL")
        self.gridLayout.addWidget(self.SKU_LBL, 3, 0, 1, 1)
        self.SKU_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.SKU_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.SKU_TE.setObjectName("SKU_TE")
        self.gridLayout.addWidget(self.SKU_TE, 3, 1, 1, 1)
        # Caliber
        self.Caliber_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Caliber_LBL.setObjectName("Caliber_LBL")
        self.gridLayout.addWidget(self.Caliber_LBL, 4, 0, 1, 1)
        self.Caliber_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Caliber_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Caliber_TE.setObjectName("Caliber_TE")
        self.Caliber_TE.setPlaceholderText('9mm, .308, 12 gauge, 5.7x28')
        self.gridLayout.addWidget(self.Caliber_TE, 4, 1, 1, 1)
        # Type
        self.Type_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Type_LBL.setObjectName("Type_LBL")
        self.gridLayout.addWidget(self.Type_LBL, 5, 0, 1, 1)
        self.Type_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Type_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Type_TE.setObjectName("Type_TE")
        self.Type_TE.setPlaceholderText('Rifle, Pistol, Shotgun, Revolver, Upper')
        self.gridLayout.addWidget(self.Type_TE, 5, 1, 1, 1)
        # Action
        self.Action_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Action_LBL.setObjectName("Action_LBL")
        self.gridLayout.addWidget(self.Action_LBL, 6, 0, 1, 1)
        self.Action_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Action_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Action_TE.setObjectName("Action_TE")
        self.Action_TE.setPlaceholderText('Bolt, Semi, Pump, Wheel')
        self.gridLayout.addWidget(self.Action_TE, 6, 1, 1, 1)
        # Overall Length
        self.OverLength_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.OverLength_LBL.setObjectName("OverLength_LBL")
        self.gridLayout.addWidget(self.OverLength_LBL, 7, 0, 1, 1)
        self.OverLength_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.OverLength_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.OverLength_TE.setObjectName("OverLength_TE")
        self.OverLength_TE.setPlaceholderText('Overall Length in Inches')
        self.gridLayout.addWidget(self.OverLength_TE, 7, 1, 1, 1)
        # BarrelLength
        self.BarrelLength_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.BarrelLength_LBL.setObjectName("BarrelLength_LBL")
        self.gridLayout.addWidget(self.BarrelLength_LBL, 8, 0, 1, 1)
        self.BarrelLength_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.BarrelLength_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.BarrelLength_TE.setObjectName("BarrelLength_TE")
        self.BarrelLength_TE.setPlaceholderText('Barrel Length in Inches')
        self.gridLayout.addWidget(self.BarrelLength_TE, 8, 1, 1, 1)
        # Weight
        self.Weight_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Weight_LBL.setObjectName("Weight_LBL")
        self.gridLayout.addWidget(self.Weight_LBL, 9, 0, 1, 1)
        self.Weight_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Weight_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Weight_TE.setObjectName("Weight_TE")
        self.gridLayout.addWidget(self.Weight_TE, 9, 1, 1, 1)
        # Twist Rate
        self.Twist_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Twist_LBL.setObjectName("Twist_LBL")
        self.gridLayout.addWidget(self.Twist_LBL, 10, 0, 1, 1)
        self.Twist_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Twist_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Twist_TE.setObjectName("Twist_TE")
        self.gridLayout.addWidget(self.Twist_TE, 10, 1, 1, 1)
        # Thread
        self.Thread_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Thread_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Thread_TE.setObjectName("Thread_TE")
        self.gridLayout.addWidget(self.Thread_TE, 11, 1, 1, 1)
        self.Thread_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Thread_LBL.setObjectName("Thread_LBL")
        self.gridLayout.addWidget(self.Thread_LBL, 11, 0, 1, 1)
        # Notes
        self.Notes_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Notes_LBL.setObjectName("Notes_LBL")
        self.gridLayout.addWidget(self.Notes_LBL, 12, 0, 1, 1)
        self.Notes_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Notes_TE.setMaximumSize(QtCore.QSize(16777215, 300))
        self.Notes_TE.setObjectName("Notes_TE")
        self.gridLayout.addWidget(self.Notes_TE, 12, 1, 1, 1)
        # Picture
        self.Picture_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Picture_LBL.setObjectName("Picture_LBL")
        self.gridLayout.addWidget(self.Picture_LBL, 13, 0, 1, 1)
        self.Picture_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Picture_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Picture_TE.setObjectName("Picture_TE")
        self.Picture_TE.setPlaceholderText('c:\pictures\picture.jpg')
        self.gridLayout.addWidget(self.Picture_TE, 13, 1, 1, 1)
        
        # Slot 16
        self.Slot_16_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_16_LBL.setObjectName("Slot_16_LBL")
        self.gridLayout.addWidget(self.Slot_16_LBL, 0, 2, 1, 1)
        self.Slot_16_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_16_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_16_TE.setObjectName("Slot_16_TE")
        self.gridLayout.addWidget(self.Slot_16_TE, 0, 3, 1, 1)
        # Slot 17
        self.Slot_17_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_17_LBL.setObjectName("Slot_17_LBL")
        self.gridLayout.addWidget(self.Slot_17_LBL, 1, 2, 1, 1)
        self.Slot_17_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_17_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_17_TE.setObjectName("Slot_17_TE")
        self.gridLayout.addWidget(self.Slot_17_TE, 1, 3, 1, 1)
        # Slot 18
        self.Slot_18_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_18_LBL.setObjectName("Slot_18_LBL")
        self.gridLayout.addWidget(self.Slot_18_LBL, 2, 2, 1, 1)
        self.Slot_18_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_18_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_18_TE.setObjectName("Slot_18_TE")
        self.gridLayout.addWidget(self.Slot_18_TE, 2, 3, 1, 1)
        # Slot 19
        self.Slot_19_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_19_LBL.setObjectName("Slot_19_LBL")
        self.gridLayout.addWidget(self.Slot_19_LBL, 3, 2, 1, 1)
        self.Slot_19_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_19_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_19_TE.setObjectName("Slot_19_TE")
        self.gridLayout.addWidget(self.Slot_19_TE, 3, 3, 1, 1)
        # Slot 20
        self.Slot_20_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_20_LBL.setObjectName("Slot_20_LBL")
        self.gridLayout.addWidget(self.Slot_20_LBL, 4, 2, 1, 1)
        self.Slot_20_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_20_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_20_TE.setObjectName("Slot_20_TE")
        self.gridLayout.addWidget(self.Slot_20_TE, 4, 3, 1, 1)
        # Slot 21
        self.Slot_21_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_21_LBL.setObjectName("Slot_21_LBL")
        self.gridLayout.addWidget(self.Slot_21_LBL, 5, 2, 1, 1)
        self.Slot_21_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_21_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_21_TE.setObjectName("Slot_21_TE")
        self.gridLayout.addWidget(self.Slot_21_TE, 5, 3, 1, 1)
        # Slot 22
        self.Slot_22_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_22_LBL.setObjectName("Slot_22_LBL")
        self.gridLayout.addWidget(self.Slot_22_LBL, 6, 2, 1, 1)
        self.Slot_22_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_22_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_22_TE.setObjectName("Slot_22_TE")
        self.gridLayout.addWidget(self.Slot_22_TE, 6, 3, 1, 1)
        # Slot 23
        self.Slot_23_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_23_LBL.setObjectName("Slot_23_LBL")
        self.gridLayout.addWidget(self.Slot_23_LBL, 7, 2, 1, 1)
        self.Slot_23_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_23_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_23_TE.setObjectName("Slot_23_TE")
        self.gridLayout.addWidget(self.Slot_23_TE, 7, 3, 1, 1)
        # Slot 24
        self.Slot_24_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_24_LBL.setObjectName("Slot_24_LBL")
        self.gridLayout.addWidget(self.Slot_24_LBL, 8, 2, 1, 1)
        self.Slot_24_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_24_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_24_TE.setObjectName("Slot_24_TE")
        self.gridLayout.addWidget(self.Slot_24_TE, 8, 3, 1, 1)
        # Slot 25
        self.Slot_25_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_25_LBL.setObjectName("Slot_25_LBL")
        self.gridLayout.addWidget(self.Slot_25_LBL, 9, 2, 1, 1)
        self.Slot_25_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_25_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_25_TE.setObjectName("Slot_25_TE")
        self.gridLayout.addWidget(self.Slot_25_TE, 9, 3, 1, 1)
        # Slot 26
        self.Slot_26_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_26_LBL.setObjectName("Slot_26_LBL")
        self.gridLayout.addWidget(self.Slot_26_LBL, 10, 2, 1, 1)
        self.Slot_26_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_26_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_26_TE.setObjectName("Slot_26_TE")
        self.gridLayout.addWidget(self.Slot_26_TE, 10, 3, 1, 1)
        # Slot 27
        self.Slot_27_TE = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.Slot_27_TE.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Slot_27_TE.setObjectName("Slot_27_TE")
        self.gridLayout.addWidget(self.Slot_27_TE, 11, 3, 1, 1)
        self.Slot_27_LBL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Slot_27_LBL.setObjectName("Slot_27_LBL")
        self.gridLayout.addWidget(self.Slot_27_LBL, 11, 2, 1, 1)

        self.retranslateUi(PopUp_Add_Firearm)
        QtCore.QMetaObject.connectSlotsByName(PopUp_Add_Firearm)

    def retranslateUi(self, PopUp_Add_Firearm):
        _translate = QtCore.QCoreApplication.translate
        PopUp_Add_Firearm.setWindowTitle(_translate("PopUp_Add_Firearm", "Add Firearm"))
        self.Name_LBL.setText(_translate("PopUp_Add_Firearm", "Name"))
        self.BarrelLength_LBL.setText(_translate("PopUp_Add_Firearm", "Barrel Length"))
        self.Weight_LBL.setText(_translate("PopUp_Add_Firearm", "Weight"))
        self.OverLength_LBL.setText(_translate("PopUp_Add_Firearm", "Overall Length"))
        self.Manufacturer_LBL.setText(_translate("PopUp_Add_Firearm", "Manufacturer"))
        self.Action_LBL.setText(_translate("PopUp_Add_Firearm", "Action Type"))
        self.Notes_LBL.setText(_translate("PopUp_Add_Firearm", "Notes"))
        self.Model_LBL.setText(_translate("PopUp_Add_Firearm", "Model"))
        self.Caliber_LBL.setText(_translate("PopUp_Add_Firearm", "Caliber"))
        self.Twist_LBL.setText(_translate("PopUp_Add_Firearm", "Twist Rate"))
        self.Thread_LBL.setText(_translate("PopUp_Add_Firearm", "Thread Size"))
        self.SKU_LBL.setText(_translate("PopUp_Add_Firearm", "SKU"))
        self.Type_LBL.setText(_translate("PopUp_Add_Firearm", "Type"))
        self.Picture_LBL.setText(_translate("PopUp_Add_Firearm", "Picture"))
        self.Slot_16_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 16"))
        self.Slot_17_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 17"))
        self.Slot_18_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 18"))
        self.Slot_19_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 19"))
        self.Slot_20_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 20"))
        self.Slot_21_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 21"))
        self.Slot_22_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 22"))
        self.Slot_23_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 23"))
        self.Slot_24_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 24"))
        self.Slot_25_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 25"))
        self.Slot_26_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 26"))
        self.Slot_27_LBL.setText(_translate("PopUp_Add_Firearm", "Slot 27"))


        self.AddFirearm_BTN.setText(_translate("PopUp_Add_Firearm", "Add Firearm"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PopUp_Add_Firearm = QtWidgets.QMainWindow()
    ui = Ui_PopUp_Add_Firearm()
    ui.setupUi(PopUp_Add_Firearm)
    PopUp_Add_Firearm.show()
    sys.exit(app.exec_())
